### ISSUE TITLE
Adapt new project setup and documentation style

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light#3]
**Tasks**
- [x] Refactor the `.gitignore` and `.gitattributes` files
- [x] Delete all outdated project files
- [x] Update the `README.md`, `CHANGELOG.md` and `LICENSE.md` files to the new documentation style
- [x] Move to the Apache 2.0 license
- [x] Add the new project branding assets (SVG and AI files)

Detailed information can be found in the milestone backlog issue #2.
