### ISSUE TITLE
Rewrite Sass sources

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light#4]
### Tasks
- [x] Rename all variables to the new naming scheme
- [x] Write SassDoc
- [x] Add the new color
- [x] Create SassDoc configuration dotfile `.sassdocrc`
- [x] Implement the `template-css.scss` file
- [x] Move files to the new `src/sass` directory

Detailed information can be found in the milestone backlog issue #2.
